global:
  marketplace-ami: false
  owner: quickstart@amazon.com
  prod-s3-path: 's3://quickstart-reference/aws/vpc'
  qsname: quickstart-aws-vpc
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
tests:
  defaults:
    parameter_input: aws-vpc-defaults.json
    template_file: aws-vpc.template
  complete-us-east-1:
    parameter_input: aws-vpc-complete.json
    regions:
      - us-east-1
    template_file: aws-vpc.template
