global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-hashicorp-consul
  regions:
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-2
  reporting: true
tests:
  consul:
    parameter_input: quickstart-hashicorp-consul-master.json
    template_file: quickstart-hashicorp-consul-master.template
    regions:
    - ap-southeast-2
    - eu-west-1
    - us-west-2
    - us-east-1
